apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager
spec:
  selector:
    matchLabels:
      app: password-manager
  template:
    metadata:
      labels:
        app: password-manager
    spec:
      containers:
      - name: password-manager
        image: <add ur docker hub repo here>:$Docker_tag
        imgaePullPolicy : ifNotPresent
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: password-manager-service
  labels:
    app: password-manager
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32000
    protocol: TCP
    name: http
  selector:
    app: password-manager
